services:
  mariadb:
    image: mariadb:11.4
    container_name: oldboyapp-db
    restart: always
    command: ["mariadbd", "--bind-address=0.0.0.0"]
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:7.4-alpine
    container_name: oldboyapp-redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: oldboyapp-backend
    restart: always
    env_file:
      - ./env.prod
    depends_on:
      - mariadb
      - redis

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: oldboyapp-frontend
    restart: always

  nginx:
    image: nginx:1.27-alpine
    container_name: oldboyapp-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend

volumes:
  mariadb_data:
